### ISSUE TITLE
error of processing SUNRGBD

### ISSUE THREAD

**Issue by sleepat-11** [TUI-NICR/nicr-scene-analysis-datasets#1]
hi,i am trying to process SUNRGBD dataset, and this error occured:
- File "prepare_data/nicr-scene-analysis-datasets/nicr_scene_analysis_datasets/datasets/sunrgbd/prepare_dataset.py", line 346, in main
    if mask.sum() == 0:
AttributeError: 'bool' object has no attribute 'sum'

how to solve this problem? any suggestion will be helpful!

**Comment by Tripton** [comment]
I think you tried to create SUNRGBD without the instances (`--create-instances` argument when running the script).
As a result, the instances could not be loaded in the following steps, which resulted in the error.
I have pushed a new commit, which hopefully resolves your issue.
