### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'to'

### ISSUE THREAD

**Issue by sleepat-11** [TUI-NICR/nicr-scene-analysis-datasets#2]
hi, i am trying to run NYUV2 panoptic segmentation on detectron2 and use Mask2former  following [this link](https://github.com/TUI-NICR/EMSANet/tree/main/external),and this error occured:  

- File "/mnt/data/lyf/Mask2Former/mask2former/maskformer_model.py", line 193, in forward
    images = [x["image"].to(self.device) for x in batched_inputs]
  File "/mnt/data/lyf/Mask2Former/mask2former/maskformer_model.py", line 193, in <listcomp>
    images = [x["image"].to(self.device) for x in batched_inputs]
AttributeError: 'numpy.ndarray' object has no attribute 'to'

similar problem is [here](https://github.com/facebookresearch/detectron2/issues/295)
do i need to change the code in [d2/utils.py](https://github.com/TUI-NICR/nicr-scene-analysis-datasets/blob/main/nicr_scene_analysis_datasets/d2/utils.py)?
[here](https://github.com/sleepat-11/codenote/blob/main/train_nyupan.py) is my code, any suggestion will be helpful!

**Comment by Tripton** [comment]
The reason for this is that our mapper first loads the data only as a numpy array. To turn the data into a torch tensor, another mapper was used in the referenced code from the EMSANet repo ([PanopticDeeplabDatasetDictMapper](https://github.com/TUI-NICR/EMSANet/blob/0559cef19e6fc6589e88996d9e9d4ef998ceae03/external/dataset_mapper.py#L77)). This also prepares the data for the panoptic segmentation. Therefore, you have to use this mapper or write your own. For reference, you can compare your [build_train_loader](https://github.com/sleepat-11/codenote/blob/f7e8a69390f0cf784b98f6c4768b15404cb860d1/train_nyupan.py#L128) and [build_test_loader](https://github.com/sleepat-11/codenote/blob/f7e8a69390f0cf784b98f6c4768b15404cb860d1/train_nyupan.py#L134) method with the one in EMSANet (found [here](https://github.com/TUI-NICR/EMSANet/blob/0559cef19e6fc6589e88996d9e9d4ef998ceae03/external/train_net.py#L125) and [here](https://github.com/TUI-NICR/EMSANet/blob/0559cef19e6fc6589e88996d9e9d4ef998ceae03/external/train_net.py#L146)).
Please try to adapt your code to this and see if it works.
