### ISSUE TITLE
Any plans for supporting Semantic KITTI?

### ISSUE THREAD

**Issue by yhs-ai** [TUI-NICR/nicr-scene-analysis-datasets#5]
Dear authors,

Hello, thank you for your great work for handling various datasets conveniently.
I wonder do you guys have any plans for supporting Semantic KITTI dataset.
If not, what branch of folder should I modify to preprocess Semantic KITTI?

Thank you.

**Comment by danielS91** [comment]
Currently, we are focusing on indoor. So there are no plans for any other outdoor dataset. However, adding a new dataset is straightforward. Just have a look at the base class and the other datasets.
